import { Platform, StyleSheet } from 'react-native';
import { screenHeight, screenWidth} from '../utils/Constants';
import {RFValue} from 'react-native-responsive-fontsize';
import {Colors} from '../utils/Constants'

export const prepareStyles = StyleSheet.create({
  image: {
    width: 40,
    height: 40,
    borderRadius: 40,
    alignSelf: 'center',
  },
  joinButton: {
    padding: 15,
    paddingHorizontal: 20,
    backgroundColor: '#fff',
    borderRadius: 10,
    margin: 10,
  },
  joinButtonText: {
    color: '#000',
    textAlign: 'center',
    fontFamily: 'Roboto-Medium',
    fontSize: RFValue(13),
  },
  container: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  meetingCode: {
    fontFamily: 'Roboto-Regular',
    fontSize: RFValue(18),
    textAlign: 'center',
    marginTop: 20,
    fontWeight: 'bold',
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
  camera: {
    width: 200,
    marginVertical: 20,
    height: 300,
    overflow: 'hidden',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#111',
    borderRadius: 18,
    position: 'relative',
  },
  localVideo: {
    width: '100%',
    height: '100%',
  },
  videoContainer: {
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: '#ccc',
    paddingBottom: 20,
  },
  toggleContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 10,
    position: 'absolute',
    bottom: 10,
    width: '100%',
  },
  iconButton: {
    marginHorizontal: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    padding: 8,
    borderRadius: 25,
    width: 45,
    height: 45,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonContainer: {
    padding: 10,
    margin: 10,
    borderWidth: 1,
    borderColor: '#ccc',
    gap: 5,
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  buttonText: {
    fontFamily: 'OpenSans-Medium',
    fontSize: RFValue(11),
    textAlign: 'center',
  },
  peopleText: {
    fontFamily: 'OpenSans-Regular',
    fontSize: RFValue(12),
    textAlign: 'center',
  },
  flexRowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  flexRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
    marginVertical: 20,
  },
  infoContainer: {
    padding: 12,
    paddingVertical: 25,
  },
  joinContainer: {
    alignItems: 'center',
    backgroundColor: '#3F4048FF',
    paddingTop: 10,
    position: 'absolute',
    bottom: 0,
    width: '100%',
    paddingBottom: Platform.OS === 'ios' ? 40 : 20,
    borderRadius: 20,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  joiningText: {
    fontFamily: 'Roboto-Medium',
    fontSize: RFValue(12),
    width: '80%',
    textAlign: 'left',
  },
  linkHeader: {
    fontSize: RFValue(12),
    color: '#333',
    marginBottom: 5,
    fontFamily: 'OpenSans-Regular',
  },
  linkText: {
    fontSize: RFValue(11),
    color: '#007AFF',
    fontFamily: 'OpenSans-Regular',
  },
  complianceHeader: {
    fontSize: RFValue(14),
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: RFValue(12),
    marginTop: RFValue(20),
    marginLeft: RFValue(10),
    fontFamily: 'Roboto-Bold',
    textAlign: 'left',
    letterSpacing: 0.5,
  },
  complianceText: {
    fontSize: RFValue(11),
    color: '#374151',
    lineHeight: RFValue(18),
    marginBottom: RFValue(6),
    marginLeft: RFValue(10),
    fontFamily: 'OpenSans-Regular',
    fontWeight: '400',
  },
  legalLinks: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: RFValue(12),
    marginBottom: RFValue(12),
    marginLeft: RFValue(10),
    justifyContent: 'flex-start',
  },
  joinButtonMain: {
    backgroundColor: '#000000',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 20,
    marginBottom: 16,
    alignSelf: 'center',
    minWidth: 160,
  },
  joinButtonMainText: {
    color: '#FFFFFF',
    fontSize: RFValue(14),
    fontWeight: '600',
    textAlign: 'center',
    fontFamily: 'Roboto-Medium',
    letterSpacing: 0.3,
  },
  disclaimerText: {
    fontSize: RFValue(10),
    color: '#6B7280',
    lineHeight: RFValue(16),
    textAlign: 'justify',
    fontFamily: 'OpenSans-Regular',
    fontWeight: '400',
    marginTop: RFValue(12),
    marginLeft: RFValue(10),
    marginRight: RFValue(10),
  },
  avatarContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#007AFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    fontSize: RFValue(30),
    fontWeight: 'bold',
    color: '#FFFFFF',
    fontFamily: 'Roboto-Bold',
  },
  userPhoto: {
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 3,
    borderColor: '#007AFF',
  },
});